import { AiFillExclamationCircle } from "react-icons/ai";
import { Link } from "react-router-dom";

export default function AboutUs() {
  return (
    <div className="mt-8 my-container">
      <div className="mt-16 text-white space-y-6">
        <h1 className="text-5xl  font-semibold">Our Passion for Literature</h1>
        <h3 className="text-lg">
          Welcome to{" "}
          <span className="text-primary">
            <Link to="/">Readers Hub</Link>
          </span>
          ! We're a community of book enthusiasts who believe in the
          transformative power of words. Our mission is simple: to ignite
          curiosity, foster inclusivity, and celebrate the magic of reading.
        </h3>
        <h1 className="text-3xl font-semibold">What We Offer</h1>
        <ul className="text-lg space-y-2">
          <li>
            <span className="text-xl">Book Reviews:</span> Dive into our
            thoughtfully crafted book reviews. Whether you're seeking a gripping
            thriller or a heartwarming romance, we've got you covered.
          </li>
          <li>
            <span className="text-xl">Author Spotlights:</span> Discover the
            faces behind the stories. Our author spotlights introduce you to
            talented writers from diverse backgrounds.
          </li>
          <li>
            <span className="text-xl">Reading Recommendations:</span> Need your
            next literary adventure? Explore our curated reading lists and find
            your next favorite book.
          </li>
        </ul>
        <h1 className="text-3xl font-semibold">Our Commitment</h1>
        <h3 className="text-lg">
          We're committed to quality content. Every article, recommendation, and
          review is meticulously curated to enhance your reading experience.
        </h3>
        <h3 className="text-lg pt-7 pb-12">
          Feel free to customize this content to align with your website's voice
          and style. Happy reading! 📚✨
        </h3>

        <h4 className="border-2 border-red-500 text-red-500 p-4 rounded-lg flex items-center gap-4">
          <AiFillExclamationCircle />
          Disclaimer: The text content on this page is generated by AI.
        </h4>
      </div>
    </div>
  );
}
